version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: which bundler?
          command: bundle -v

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-v2-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-v2-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3

      - save_cache:
          paths:
            - vendor/bundle
          key: dependencies-v2-{{ checksum "Gemfile.lock" }}

      - run:
          name: run tests
          command: |
            bundle exec rake

      # collect reports
      - store_test_results:
          path: ~/repo/test/reports
      - store_artifacts:
          path: ~/repo/test/reports
          destination: test-results
