version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3

      - save_cache:
          paths:
            - ./venv
          key: dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: run tests
          command: |
            rake

      # collect reports
      - store_test_results:
          path: ~/repo/test/reports
      - store_artifacts:
          path: ~/repo/test/reports
          destination: test-results
